# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpm" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "cac39e0a07bcf5ae2588cd97d737d99c8aa723462ddf73740d4a5eb78c888d1a"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "4aa389acf7a08bbe9732f1fed177ffbe8a1874e1f904bb9cb3a272f737bcdf39"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "fd4950200d12f27a0270ef8fcf9c86137682b84b449e4b874716a066bd04b545"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "93c24c20c245a801d653b913bc63559d845b00052ec854aabee0ae07152f4a8d"
    end
  end

  name "mcpm"
  desc "Local-first control plane for discovering and operating MCP servers"
  homepage "https://github.com/draxel-ai/mcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpm"]
    end
  end

  # No zap stanza required

end
