# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpm" do
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "3cd23f94e9497b6bad81070c7029742c9570ea650e5534ab09dd0cb6fd285d1d"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "f5bd022979cf0cb12c3c74caf9a4063e9937dfca8a99e13e69633d585dee5b92"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "246014873969437bd7ce0fedfea3d8a619ffb9988baac7ed95637f8d3d9e04c6"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "aeb9e40699291dd9c957da4c56c2f55aa8e582779a7c6f256b45324e6004114c"
    end
  end

  name "mcpm"
  desc "Local-first control plane for discovering and operating MCP servers"
  homepage "https://github.com/draxel-ai/mcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpm"]
    end
  end

  # No zap stanza required

end
