# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcpm" do
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "abb4005f9ed6e242109b6f9b407908b7aca49e23be6791c6286c3bb8aec285d8"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "ebd12c02a0bdd8756ce685ce40b4ecdb83648831e46bf33c210bf08b66190b10"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "bd497efb9ee5007c5f23d1e59cacbe3d950933a13a67e76d20235fb87be94289"
    end
    on_arm do
      url "https://github.com/draxel-ai/mcpm/releases/download/v#{version}/mcpm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/draxel-ai/mcpm/"
      sha256 "d181971de8f248c09118aff035529297c78d059a7f004ec628b8cd90671e3721"
    end
  end

  name "mcpm"
  desc "Local-first control plane for discovering and operating MCP servers"
  homepage "https://github.com/draxel-ai/mcpm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcpm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcpm"]
    end
  end

  # No zap stanza required

end
